services:
  # Backend API Service
  - type: web
    name: calibration-backend
    runtime: node
    region: oregon
    plan: starter
    buildCommand: cd backend && npm install && npm run prisma:generate && npm run build
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: calibration-db
          property: connectionString
      - key: JWT_ACCESS_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: JWT_ACCESS_EXPIRES_IN
        value: 15m
      - key: JWT_REFRESH_EXPIRES_IN
        value: 7d
      - key: CORS_ORIGIN
        fromService:
          type: web
          name: calibration-frontend
          property: host
      - key: RATE_LIMIT_WINDOW_MS
        value: 900000
      - key: RATE_LIMIT_MAX
        value: 100
      - key: LOG_LEVEL
        value: info
    healthCheckPath: /api/health

  # Frontend Static Site
  - type: web
    name: calibration-frontend
    runtime: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/dist
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: calibration-backend
          property: host
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

databases:
  - name: calibration-db
    databaseName: calibration_production
    region: oregon
    plan: starter
